### ISSUE TITLE
Upgrade all deployment platforms to Ubuntu 14.04.5

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#1813] opened 2017-06-20 14:59 UTC
We are using Ubuntu 14.04.2 on Vagrant and AWS at the moment. [Travis CI is in the process of moving to the latest version of 14.04.5](https://blog.travis-ci.com/2017-06-19-trusty-updates-2017-Q2) ~~and it is causing builds to fail~~.

Ubuntu 14.04.5 is the latest in the 14.04 LTS series, while 14.04.2 is almost 2.5 years old at this point (https://wiki.ubuntu.com/Releases).

We should standardize on Ubuntu 14.04.5 across all deployment platforms (Vagrant, Travis and AWS).

We should probably [constrain](https://www.vagrantup.com/docs/boxes/versioning.html#version-constraints) Vagrant environment to a specific version of the Ubuntu box using the Vagrantfile by specifying the `config.vm.box_version` option.

**Comment by mccalluc** [comment] 2017-06-21 17:32
Huh: So my last build was on the new version, and there weren't any problems. Don't know whether I wasn't building the right way before, or if they put in some last minute fixes.
- Removing "critical" here
- and I'll delete my experimental branches.

**Comment by hackdna** [comment] 2017-06-21 18:20
FWIW, my [build](https://travis-ci.org/refinery-platform/refinery-platform/builds/245479188) just failed:
```
$ bower install --config.interactive=false --quiet
module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (/home/travis/.nvm/versions/node/v7.4.0/lib/node_modules/bower/lib/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)


The command "bower install --config.interactive=false --quiet" failed and exited with 1 during .

Your build has been stopped.
```

**Comment by mccalluc** [comment] 2017-06-21 18:28
Oh, yeah, that's the error I had seen when I tried the preview. Maybe it wasn't deployed across the whole pool yet. who knows. 

- "critcal" back on
- but I'll also make a PR to use the old version, now that it's available.

**Comment by mccalluc** [comment] 2017-07-17 20:19
Picking this up again. Builds still fail the same way as quoted above. How we configure Vagrant and AWS is something I don't know, so I'll start looking into that.

**Comment by mccalluc** [comment] 2017-07-17 21:32
Note: We want to upgrade to the latest `trusty`, not jump to `xenial`... and if we did we might be [out of luck](https://bugs.launchpad.net/cloud-images/+bug/1569237): The xenial images are not following Vagrant conventions and are prompting for a password on startup.

**Comment by mccalluc** [comment] 2017-07-17 21:53
In local vagrant: 
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```
on [travis](https://travis-ci.org/refinery-platform/refinery-platform/builds/254501296#L16):
```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

so I don't have quite the right version, and I don't see the bower error.

**Comment by mccalluc** [comment] 2017-07-18 13:59
So on the list of [official Ubuntu images for Vagrant](https://app.vagrantup.com/ubuntu/boxes/trusty64)  it says 
>  Externally hosted (cloud-images.ubuntu.com)

When I go there and [click through to trusty](http://cloud-images.ubuntu.com/trusty/) all the pages below that say `Ubuntu 14.04.5 LTS (Trusty Tahr) Daily Build` in the header.

* My vagrant image is 14.04.4, but at the ostensible source, everything is 14.04.5...
* but even then, I think I want a `.box` file, and I don't see that here.

So that confuses me.

Alternatively, on [this 3rd party site](http://www.vagrantbox.es/) there's a [14.04.5 from some dude](https://github.com/sepetrov/trusty64/releases/download/v0.0.5/trusty64.box). I don't think we'd want to build on that.

Should I look into what exactly makes a `.box` file?

**Comment by mccalluc** [comment] 2017-07-18 14:42
I must just have been sloppy. 
```
vagrant@refinery:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

vagrant@refinery:~$ cd /vagrant/refinery/ui/

vagrant@refinery:/vagrant/refinery/ui$ bower install --config.interactive=false --quiet
```

No error... but actually I was hoping for the same error as Travis, so this is not a success.

**Comment by mccalluc** [comment] 2017-07-18 14:46
My next guess is that something different than the base operating system is causing the difference in bower/npm behavior. Get version numbers and see if there are mismatches.

**Comment by drj11** [comment] 2017-07-18 14:48
So, perhaps it is just Travis being unreliable, and not particularly related to Ubuntu 14.04.5.

It's possible that Travis new pool of machine / VMs / whatever they use, is unreliable is some unrelated, but correlated, way.

**Comment by mccalluc** [comment] 2017-07-18 16:48
On [travis](https://travis-ci.org/refinery-platform/refinery-platform/builds/254919350#L509)
```
$ npm --version
4.0.5
```
 I think that [3.10.10](https://github.com/npm/npm/releases/tag/v3.10.10) is the most recent 3.x release. I'll look at downgrading NPM on travis:
- Moving toward the version that works (if this is actually the cause)
- Moving toward what we get out of the box from Vagrant

**Comment by mccalluc** [comment] 2017-07-18 17:07
Same failure even with [NPM downgrade](https://travis-ci.org/refinery-platform/refinery-platform/builds/254941880#L606). Look at version of node itself.

**Comment by drj11** [comment] 2017-07-19 07:52
I think you can use npm to install different versions of node.

**Comment by mccalluc** [comment] 2017-07-19 13:17
Maybe you mean something like https://davidwalsh.name/upgrade-nodejs ? It looks like that's deprecated in favor of nvm.

**Comment by hackdna** [comment] 2017-10-17 19:34
Currently ami-d05e75b8 is [hardcoded in stack.py](https://github.com/refinery-platform/refinery-platform/blob/develop/deployment/stack.py#L186) which is Ubuntu 14.04.2.

**Closed** 2019-02-12 15:38 UTC
Labels: cloud, deployment, important, technical debt, tests, travis-ci
