### ISSUE TITLE
Upgrade postgresql on all deployment platforms

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2865] opened 2018-07-16 13:10 UTC
The following is an Email to @ngehlenborg stating that: `Amazon RDS will be discontinuing support for version 9.3 of the PostgreSQL database in RDS, starting on September 5th, 2018`.

We should upgrade to a supported version on for our AWS deployment as well as within Vagrant & Travis CI for consistency. We should also think about what this means for any RDS snapshots that currently encapsulate a postgres 9.3 db.

```
Hello,

This notification is being sent to you to as a reminder that Amazon RDS will be discontinuing support for version 9.3 of the PostgreSQL database in RDS, starting on September 5th, 2018. 

Amazon RDS has been supporting the PostgreSQL major version 9.3 since 2013. That release has since been replaced by subsequent major versions that contain significant improvements in functionality, security, reliability and performance. The PostgreSQL community has announced the end of life date for PostgreSQL 9.3 as September 2018 [1].  Aligning with the community support model, AWS will be ending support for the PostgreSQL major version 9.3 in Amazon RDS, including its minor engine versions including 9.3.10, 9.3.12, 9.3.14, 9.3.16, 9.3.17, 9.3.19, 9.3.20, and 9.3.22. We will continue to support 9.4 and more recent versions of the PostgreSQL database on Amazon RDS.

We recommend that you upgrade your Amazon RDS PostgreSQL database instances to either version 9.6 or version 10 at your earliest convenience. You can use the Major Version Upgrade feature of RDS to upgrade databases to the next higher version. You can initiate an upgrade by going to the Modify DB Instance page in the AWS Management Console and changing the database version setting to a newer major version of PostgreSQL. If you choose the "Apply Immediately" option, the upgrade will be initiated immediately after exiting the Modify page. If you choose not to apply the change immediately, the upgrade will be performed during your subsequent maintenance window.  To learn more about upgrading PostgreSQL major versions in RDS, review the Upgrading Database Versions page [2].

As part of the retirement plan for Amazon RDS PostgreSQL 9.3, starting the week of August 6th 2018, you will no longer be able to create any new PostgreSQL 9.3 instances using the AWS console. In November  2018, your remaining 9.3 instances will be force upgraded to the most recent minor version of PostgreSQL 9.4. Once this occurs, any instance restored from a snapshot of a deprecated version will automatically and immediately be upgraded to a currently supported version. The exact dates and details on force upgrades will be communicated in September 2018.

Your affected instances in US-EAST-1 Region:
scc-beta
rds-refinery-of963ie
princeton-bii-demo


Should you have any questions or concerns, the AWS Support Team is available on the community forums and via Premium Support [3]. To learn more about Amazon RDS policy for supporting database versions, please see [4].

[1] https://www.postgresql.org/support/versioning/
[2] https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html
[3] https://aws.amazon.com/support
[4] https://aws.amazon.com/rds/faqs/ [search for "guidelines for deprecating database engine versions"]

Sincerely,
Amazon Web Services

Amazon Web Services, Inc. is a subsidiary of Amazon.com, Inc. Amazon.com is a registered trademark of Amazon.com, Inc. This message was produced and distributed by Amazon Web Services Inc., 410 Terry Ave. North, Seattle, WA 98109-5210

---
Reference: https://phd.aws.amazon.com/phd/home#/event-log?Event%20ARN=arn:aws:health:us-east-1::event/AWS_RDS_OPERATIONAL_NOTIFICATION_b95fab51-2fdb-400d-bddf-e3250cb7eaf9&eventID=arn:aws:health:us-east-1::event/AWS_RDS_OPERATIONAL_NOTIFICATION_b95fab51-2fdb-400d-bddf-e3250cb7eaf9&eventTab=details&layout=vertical
```

**Comment by hackdna** [comment] 2018-07-16 14:12
Duplicate of #2707

**Closed** 2018-07-16 15:15 UTC
Labels: aws, database, technical debt, travis-ci
