### ISSUE TITLE
Analysis filters do not work reliably in FB2 when url params already set

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2081] opened 2017-09-05 18:42 UTC
* Specific code commit: 24dd3c679983467e6f75de8a9858b2bfbc33d853

### Steps to reproduce

1. Login
2. On a data set you have access to, run an analysis
3. Wait for analysis to complete
4. Enter the file browser, and tweak some facets other than analysis
5. Add an analysis facet

It seems to be ignored. (Every time? Are there other variables? @scottx611x)

6. Reload the page, try the same facet, and this time it works.

**Comment by jkmarx** [comment] 2017-10-24 13:49
Could not reproduce, but possibly resolved by pull request #2262 

This is post-analysis
![analysis-filter-bug2](https://user-images.githubusercontent.com/9956764/31946720-8e3f163e-b8a0-11e7-9575-21413a9f2cfa.gif)

**Closed by jkmarx** 2017-10-24 13:49 UTC
Labels: bug, ui
