### ISSUE TITLE
Data Set Import -> Associated data files waiting to be uploaded bug

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#2691] opened 2018-03-23 12:22 UTC
* Specific code commit: 07fa2fc90223e14336c5547c4d8238ec03fd648b
* Version of the web browser and OS: Chrome
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Test instance

### Steps to reproduce
Please list all the actions and the input data used:

1. Metadata Import or Isatab Import, add file
2. Select add data sets and add any file

### Observed behavior
![screen shot 2018-03-23 at 8 14 07 am](https://user-images.githubusercontent.com/9956764/37828760-e2fb490c-2e72-11e8-8788-08aea7c83da1.png)

### Expected behavior
* When you have data files selected, you should not be able to upload without adding them. 

https://github.com/refinery-platform/refinery-platform/commit/14c9190d8565a8c09cf866d8982690a01116aec5

**Comment by hackdna** [comment] 2018-03-23 13:25
Looks like a duplicate of #2412

**Comment by hackdna** [comment] 2018-07-31 14:34
This issue just came up again during data set import by the bioinfo core. Priority requested by @sjhosui.

**Closed** 2018-08-14 14:49 UTC
Labels: HSCI requested, bug, import, important
