### ISSUE TITLE
File browser columns in config in reverse order

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2208] opened 2017-09-29 15:14 UTC
* Specific code commit: ?
* Version of the web browser and OS: ?
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): ?

### Steps to reproduce
Please list all the actions and the input data used:

1. ?
2. ?

### Observed behavior

Chuck is not reproducing this: I uploaded a new csv and got this:
![screen shot 2017-09-29 at 11 11 26 am](https://user-images.githubusercontent.com/730388/31022476-ebc1d538-a506-11e7-9459-1312f02deb3c.png)

@gmnelson or @sjhosui : Could you pass me a file which demonstrates the problem for you?

**Comment by sjhosui** [comment] 2017-09-29 16:05
Do an upload of this ISA-tab by URL.

http://stemcellcommons.org/sites/default/files/isa/isa_16171_733110.zip<http://stemcellcommons.org/sites/default/files/isa/isa_14911_906861.zip>

This is what I observe when I open the config. Note that column order in the table is different from the Config listing. Now if I close it without doing anything, nothing changes (as expected) but it could be confusing if you wanted Genetic Transformation to be the first column, for example.

[cid:464424B9-7FB6-4EB7-997B-5AB9217EF25D]

**Comment by jkmarx** [comment] 2017-09-29 16:19
@mccalluc @sjhosui @gmnelson I believe the issue is the attribute order does not sync up with the table display until a change is made. I thought there was an issue for this already, but it must have slipped through the cracks.

**Comment by sjhosui** [comment] 2017-09-30 00:29
Yes, that sounds like the one.

Thanks,
Shannan

**Comment by jkmarx** [comment] 2018-03-14 14:09
Issues #2025 encompasses this one.

**Closed by jkmarx** 2018-03-14 14:09 UTC
