### ISSUE TITLE
Spurious slashes added to source name of data set files

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2582] opened 2018-02-09 15:29 UTC
* Specific code commit: c1e0b37
* Version of the web browser and OS: any
* Environment where the error occurred: any

### Steps to reproduce
1. Import a [tabular metadata file](http://data.cloud.refinery-platform.org.s3.amazonaws.com/data/sample-data/human-chipseq/hg19-metadata-local.txt)
1. Expand data set preview or navigate to data set details

### Observed behavior
Source names are displayed as follows: `s/7/_/E/V/_/E/2/_/4/5/m/i/n/./s/u/b/s/a/m/p/l/e` and `s/5/_/p/4/2/_/E/2/_/4/5/m/i/n`

### Expected behavior
Source names displayed correctly without extra slash characters

**Comment by jkmarx** [comment] 2018-03-14 14:35
duplicate of #2340

**Closed by jkmarx** 2018-03-14 14:35 UTC
Labels: HSCI requested feature, bug, dataset, files, import, important, metadata
