### ISSUE TITLE
Links in pop-overs are un-clickable

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1886] opened 2017-07-10 19:31 UTC
* Specific code commit: bc425b3403264b8a0fb1d28cd412a7360e05dc6b
* Version of the web browser and OS: both ff and chrome, macos
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): production, test instance

### Steps to reproduce
Please list all the actions and the input data used:

1. On the dashboard, click on dataset you own to get a preview to fold out
1. Click on "share" above the right pane: This brings up "Permission Editor"
1. Click on the question mark to bring up the "Share a Data Set" popover
1. Click on a link in the popover

or, in file-upload

1. click on the "?" for " Column containing species names or identifiers."
### Observed behavior
* The popover closes, rather than taking you to the appropriate resource

### Expected behavior
* Links take you to the appropriate pages... but maybe it'd be easier just not to have links here?

(Should also review other pop-overs to see if they contain links, and if they are clickable.)

**Comment by scottx611x** [comment] 2017-07-11 13:23
Unable to reproduce. @mccalluc will check it out again with other browsers.

**Comment by jkmarx** [comment] 2017-10-13 12:56
I encountered this issue when updating the global analysis popover. The append-to-body option was required, but note, it will move the popover scope out of the parent's scope. I'll double check the permission editor and either fix it or close this issue.

**Comment by jkmarx** [comment] 2017-10-13 17:34
I checked the permission editor and any popover-html references. I could not reproduce this issue in chrome, firefox, or safari. @mccalluc If you reproduce, please make a giphy and reopen the issue.

**Closed by jkmarx** 2017-10-13 17:34 UTC
Labels: bug, dashboard, ui

**Comment by jkmarx** [comment] 2017-10-13 19:21
Reference #2231
